import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'
import { motion } from "framer-motion";

const PageTransition = ({ children }) => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    >
      {children}
    </motion.div>
  );
};

export default function Home() {
  return (
    <PageTransition>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <header className={styles.header}>
          <h2></h2>
        </header>
        <main className={styles.main}>
          <div  className={styles.cont_profile}>
            <div>
              <Image
                className={styles.img_profile}
                src="/images/me.png"
                width={200}
                height={300}
                alt="Profile picture of me"/>
            </div>
            <div className={styles.txt_profile}>
              <p className={styles.msg_profile}>Hi! I'm Mio Takagi.<br/>A Front-End Developer.</p>
              <Link
                className={styles.button}
                href={"https://vankurage.com/"}>
                  Check out my Portfolio
              </Link>
            </div>
          </div>
        </main>
      </div>
    </PageTransition>
  )
}
