import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'
import { motion } from "framer-motion";
import { useState, useEffect } from 'react'
import DotBackground from '@/component/background';
import TawkTo from '@/component/tawkto';
import Dot from '@/component/dot';

const PageTransition = ({ children }) => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    >
      {children}
    </motion.div>
  );
};

export default function Home() {

  return (
    <PageTransition>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="/tawk.js" async></script>
      </Head>
      <div className={styles.wrapper}>
        {/* <header className={styles.header}>
          <h2></h2>
        </header> */}
        <DotBackground />
        <TawkTo />
        <Dot />
        <main className={styles.main}>
          <div  className={styles.cont_profile}>
            <div>
              <Image
                className={styles.img_profile}
                src="/images/me.png"
                width={200}
                height={300}
                alt="Profile picture of me"/>
            </div>
            <div className={styles.txt_profile}>
              <p className={`${styles.msg_profile} ${styles.msg_profile1}`}>Hi! I'm Mio Takagi.</p>
              <p className={`${styles.msg_profile} ${styles.msg_profile2}`}>A Front-End Developer.</p>
              <Link
                style={{cursor: 'pointer'}}
                className={styles.button}
                href={"https://vankurage.com/"}>
                  <span className={styles.button_txt}>Check out my Portfolio</span>
              </Link>
            </div>
          </div>
        </main>
      </div>
    </PageTransition>
  )
}
